### ISSUE TITLE
"Web2PrintToolsBundle\Controller\AdminController" has no container set

### ISSUE THREAD

**Issue by dvesh3** [pimcore/web2print-tools#22]
```
Status: 500 | 
URL: /admin/web2printtools/admin/favorite-output-definitions-table-proxy?xaction=read&_dc=1624000754205
Method: POST
Message: "Web2PrintToolsBundle\Controller\AdminController" has no container set, did you forget to define it as a service subscriber?
Trace: 
in /www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php:39
#0 /www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php(29): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->configureController()
#1 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php(120): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->instantiateController()
#2 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php(42): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController()
#3 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php(86): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->createController()
#4 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/TraceableControllerResolver.php(38): Symfony\Component\HttpKernel\Controller\ControllerResolver->getController()
#5 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(140): Symfony\Component\HttpKernel\Controller\TraceableControllerResolver->getController()
#6 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#7 /www/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle()
#8 /www/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#9 {main}
```

**Comment by dvesh3** [comment]
duplicate #21
